<div class="rating d-inline-block position-relative align-middle z-0" data-rating="<?php print $rating; ?>">
  <div class="rating-overlay-a text-warning position-relative z-1 over-hidden">
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
  </div>
  <div class="rating-overlay-b text-black-50 position-absolute">
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
    <span class="font-m icon-shape-star"></span>
  </div>
</div>
<div class="d-inline-block font-xs text-<?php print $invert; ?> align-middle">
  (<?php print $rating; ?>/10)
</div>
